scrape_configs:
  - job_name: 'nile-application'
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: 'nile-application/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
