spring:
  application:
    name: nile-application

server:
  servlet:
    context-path: /${spring.application.name}

management:
  endpoint:
    shutdown:
      enabled: true

logging:
  level:
    tech.volkov.nilecore: debug
