spring:
  application:
    name: nile-application

server:
  servlet:
    context-path: /${spring.application.name}

management:
  endpoints.web.exposure.include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    tech.volkov.nilecore: debug
