spring:
  application:
    name: nile-application

server:
  servlet:
    context-path: /${spring.application.name}

weather:
  api-key: dfa9c4bfd52d6549908a828e0cec63b0
  requests-limit-per-minute: 60
  countries-cities-map:
    Russia:
      - Moscow
      - Saint Petersburg
      - Sochi
      - Novosibirsk
      - Ulan-ude
    USA:
      - New York
      - Los Angeles
      - Miami
    Germany:
      - Berlin
    France:
      - Paris
    United kingdom:
      - London
    Spain:
      - Barcelona
    China:
      - Beijing
    Australia:
      - Sydney

management:
  endpoints.web.exposure.include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    tech.volkov.nile: debug
